Fixed a call to .using() that didn't make it into one of the model-validation branch merges.

git-svn-id: http://code.djangoproject.com/svn/django/trunk@12106 bcc190cf-cafb-0310-a4f2-bffc1f526a37
