Use io.open and utf8 encoding to fix UnicodeDecodeError for Python3 (#8671)

